### ISSUE TITLE
CacheFrom Flag splits the value on comma

### ISSUE THREAD

**Issue by kameshsampath** [thegeeklab/drone-docker-buildx#141]
First of all thank you so much for making this plugin.

When I use `cache_from` as part of my plugin settings,

```yaml
- name: build
    image: thegeeklab/drone-docker-buildx
    privileged: true
    pull: if-not-exists
    settings:
      daemon_off: true
      dockerfile: docker/Dockerfile.pnpm
      repo: kameshsampath/drone-ci-extension-ui-base
      cache_from: 
       - "type=registry,ref=kameshsampath/docker-extension-ui-cache"
      cache_to: "type=registry,ref=kameshsampath/docker-extension-ui-cache"
      tag:
        - latest
      platforms:
        - linux/amd64
        - linux/arm64
      context: ui
```

I see the CLI splits the value on `,` and hence the resulting docker command is like,

```shell
/usr/local/bin/docker buildx build --rm=true -f docker/Dockerfile.pnpm ui --push --pull=true --cache-from type=registry,ref=kameshsampath/docker-extension-ui-cache --cache-to type=registry,ref=kameshsampath/docker-extension-ui-cache --build-arg DOCKER_IMAGE_CREATED=2022-10-29T12:57:10Z --platform linux/amd64,linux/arm64 -t kameshsampath/drone-ci-extension-ui-base:latest
```

When debugging the issue further I found that `https://github.com/urfave/cli` splits the value using `,` and that resulting in this erroneous command flags.  https://github.com/urfave/cli/blob/main/flag.go#L382
