### ISSUE TITLE
[Question] Loading Image to Local Docker Deamon

### ISSUE THREAD

**Issue by kameshsampath** [thegeeklab/drone-docker-buildx#146]
Is it possible to load the built image out of the buildx step onto the local docker daemon, I tried doing `dry_run: true` and `push: false` and mounted local docker volume thinking `--load` will happen. Think it does not. 

@xoxys  am I missing something here?

**Comment by xoxys** [comment]
Don't know what you try to achieve, but there is an [output parameter](https://drone-plugin-index.geekdocs.de/plugins/drone-docker-buildx/#parameters) available to set a custom export action for the build result. However, this is a CI plugin that is intended to run in encapsulated environments. Workarounds or hacks to export artifacts from a local volumes/storage isn't a use case I want to support.

**Comment by kameshsampath** [comment]
when I used the Drone official `plugins/docker` I set the `dry_run: true` and `purge: false` to load the image on to the Docker on the host to do some tests and checks before I can push to external repo. I am trying to achieve the same.

**Comment by xoxys** [comment]
That's due to how buildx works.

> WARNING: No output specified with docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load

As `--load` is only a [shorthand flag](https://docs.docker.com/engine/reference/commandline/buildx_build/#load) you can use the `output` plugin parameter mentioned above.

**Comment by kameshsampath** [comment]
@xoxys  the following way helped me to load it to local docker daemon,

```yaml
- name: build
    image: thegeeklab/drone-docker-buildx
    privileged: true
    pull: if-not-exists
    settings:
      dry_run: true
      output: "type=docker"
      daemon_off: true
      dockerfile: docker/Dockerfile.standalone
      cache_from:
        - 'type=registry\\,ref=kameshsampath/drone-ci-docker-extension-cache'
      cache_to: "type=registry,ref=kameshsampath/drone-ci-docker-extension-cache"
      repo: drone/drone-ci-docker-extension
      tag:
        - latest
      # keep the core context to minimum as we load named contexts
      context: docker
      named_context:
        - dist=backend/dist
        - ui=ui/build
        - scripts=backend/scripts
        - etc=etc
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
```

Since mounting host daemon via volume does not purge the created buildkit containers, may be we need to add a step in drone to clean them on host
