### ISSUE TITLE
GitHub Container Registry Insufficient Scope

### ISSUE THREAD

**Issue by tolype** [thegeeklab/drone-docker-buildx#159]
Hello! 

I am trying to push a container image to GitHub's Container Registry as part of my pipeline. I can't seem to get around an issue where, once the image has been built, Docker seemingly fails to authentication with the registry. My `.drone.yml` is below:

```yaml
kind: pipeline
type: docker
name: default

steps:
  - name: build and push to github registry
    image: ghcr.io/[user]/[repo]
    pull: always
    privileged: true
    settings:
      registry: ghcr.io
      repo: [user]/[repo]
      username: [user]
      password:
        from_secret: github_access_token
      tags: latest
      context: .
      build_args:
        - DOCKER_VERSION=20.10.22
        - GOLANG_VERSION=1.19.4
        - PLUGIN_VERSION=20.12.7
        - ARCH=amd64

image_pull_secrets:
  - dockerconfig
```

The image builds, but I get the following snippet when it starts to push to the registry:

```
. . .
#10 DONE 0.0s

#11 exporting to image
#11 exporting layers
#11 exporting layers 0.5s done
#11 exporting manifest sha256:b512029d29389dff52009b54cbc0da0a53f45604808d2c6191bc5e27248a0d1d 0.0s done
#11 exporting config sha256:6e5c12e55380317f6263205cb2c10734aa3e858cbb394b2eb53f5641c9c30304 0.0s done
#11 pushing layers
#11 pushing layers 0.4s done
#11 ERROR: server message: insufficient_scope: authorization failed
------
 > exporting to image:
------
ERROR: failed to solve: server message: insufficient_scope: authorization failed
time="2022-12-19T23:36:47Z" level=fatal msg="execution failed: exit status 1"
```

I've tried several solutions (e.g., not using secrets, using an access token with all permissions, etc.), but nothing has worked. I had assumed the the GitHub Container Registry was supported, but now I am second guessing. Any help would be greatly appreciated.
