### ISSUE TITLE
Tagging the last release as latest (and not the latest push)

### ISSUE THREAD

**Issue by kolaente** [thegeeklab/drone-docker-buildx#163]
I'm not sure if this works already or needs a PR.

I have a pipeline to build docker images on releases:

```yaml
  - name: docker-unstable
    image: thegeeklab/drone-docker-buildx
    privileged: true
    pull: true
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: vikunja/api
      tags: unstable
      platforms:
        - linux/386
        - linux/amd64
        - linux/arm/v6
        - linux/arm/v7
        - linux/arm64/v8
    depends_on: [ fetch-tags ]
    when:
      ref:
        - refs/heads/main

  - name: docker-release
    image: thegeeklab/drone-docker-buildx
    privileged: true
    pull: true
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: vikunja/api
      auto_tag: true
      platforms:
        - linux/386
        - linux/amd64
        - linux/arm/v6
        - linux/arm/v7
        - linux/arm64/v8
    depends_on: [ fetch-tags ]
    when:
      ref:
        - "refs/tags/**"
```

As you can see the pipeline builds docker images tagged `:unstable` for each push to master and releases tagged by the version of the git tag. This works great, now I also want the _last release_ to also get tagged as `:latest`. Can I just add a `tags` configuration to the `docker-release` step? Would that work with the `auto_tag` option?

The docs say:

> When the event type is push and the target branch is your default branch, the plugin will automatically tag the image as latest. All other event types and branches are ignored.

This does not automatically tag a docker image with `:latest` since the pipeline is only triggered by a git tag event, never a push to the `main` branch.
