### ISSUE TITLE
Feature Request: Push to multiple registries

### ISSUE THREAD

**Issue by Maks1mS** [thegeeklab/drone-docker-buildx#218]
It would be nice to be able to do something like this:
```yaml
kind: pipeline
name: default

steps:
  - name: docker
    image: thegeeklab/drone-docker-buildx:23
    privileged: true
    settings:
      repo-list:
        - username: octocat
          password: ****
          repo: octocat/example
        - registry: ghcr.io
          username: gh-octocat
          password: ****
          repo: ghcr.io/gh-octocat/example
        - registry: quay.io
          username: quay-octocat
          password: ****
          repo: quay.io/quay-octocat/example
          ...
```
