### ISSUE TITLE
Authentication for GCR does not work

### ISSUE THREAD

**Issue by moeen** [thegeeklab/drone-docker-buildx#277]
I have defined a `image_publish` step using your plugin:
```yaml
- name: publish_image
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    dockerfile: Dockerfile
    registry: gcr.io
    repo: <IMAGE-NAME>
    username: _json_key
    password:
      from_secret: gcr-serviceaccount
    platforms: 
      - linux/arm64
      - linux/amd64
```

This is the recommended way to login to GCR as described in [their docs](https://cloud.google.com/container-registry/docs/advanced-authentication#json-key).

But I'm getting this error:
```
ERROR: failed to solve: failed to push <IMAGE-NAME>:<IMAGE-TAG>: server message: insufficient_scope: authorization failed
```

I also used this to verify my credentials, and it worked fine and I was able to push the image:
```yaml
- name: docker_build
  image: docker:dind
  environment:
    USERNAME: _json_key
    PASSWORD:
      from_secret: gcr-serviceaccount
  commands:
    - echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin https://gcr.io
```
