### ISSUE TITLE
Multi arch builds fail

### ISSUE THREAD

**Issue by gsp8181** [thegeeklab/drone-docker-buildx#28]
When trying to build a multi architecture build, the build fails with the following error
```
#10 exporting to oci image format
--
9513 | #10 sha256:69a2560eef4d3ece902c3b5149d142e9bd132f25db0bc9e35b94201534c415d2
9514 | #10 ERROR: docker exporter does not currently support exporting manifest lists
9515 | ------
9516 | &gt; exporting to oci image format:
9517 | ------
9518 | error: failed to solve: rpc error: code = Unknown desc = docker exporter does not currently support exporting manifest lists
9519 | time="2021-06-10T23:30:53Z" level=error msg="execution failed: exit status 1"
```
This was the .drone.yml file I was using
```
kind: pipeline
type: docker
name: default
platform:
  os: linux
  arch: arm64
steps:
- name: docker  
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    repo: gsp8181/calibre-web-arm
    tags: latest
    platforms: linux/arm/v7,linux/arm64/v8
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
```

I believe this issue is caused because --load is passed as a docker buildx argument when this should be  --push for multi architecture builds.

**Comment by xoxys** [comment]
Thanks for your report. You are right that's related to `--load` which does not allow exporting manifest lists. The reason for why we use `--load` is that we want to separate the build and push step because otherwise the `dry-run` option would be difficult to handle. I'll create a test setup and try to workaround it somehow.

**Comment by mingcheng** [comment]
i have the same problem, its cost me a long night, sigh~

**Comment by xoxys** [comment]
Related: https://github.com/docker/buildx/issues/59#issuecomment-659303756

**Comment by xoxys** [comment]
@mingcheng @gsp8181 this should be fixed in the `latest` tag could one of you verify that it works as expected now?

**Comment by BitProcessor** [comment]
@xoxys it seems a new issue was introduced with this fix

This works fine:
```
kind: pipeline
type: docker
name: default

steps:
- name: docker  
  image: thegeeklab/drone-docker-buildx:latest
  privileged: true
  settings:
    context: buildx
    dockerfile: buildx/Dockerfile
    repo: bitprocessor/multiarch-drone
    tags: latest
    platforms: linux/amd64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
```

But as soon as I add arm64 as platform:
```

kind: pipeline
type: docker
name: default

steps:
- name: docker  
  image: thegeeklab/drone-docker-buildx:latest
  privileged: true
  settings:
    context: buildx
    dockerfile: buildx/Dockerfile
    repo: bitprocessor/multiarch-drone
    tags: latest
    platforms: linux/amd64,linux/arm64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
```

It fails:
```
latest: Pulling from thegeeklab/drone-docker-buildx
Digest: sha256:6fe79725a5e707aa370a8a0d1417f0d52b56029e85e964b8effa3ee27238d4bd
Status: Image is up to date for thegeeklab/drone-docker-buildx:latest
+ /usr/local/bin/dockerd --data-root /var/lib/docker --host=unix:///var/run/docker.sock
Detected registry credentials
+ /usr/local/bin/docker version
Client:
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:42:10 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:46:14 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
+ /usr/local/bin/docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.15.0-143-generic
 Operating System: Alpine Linux v3.13 (containerized)
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 62.81GiB
 Name: c77a7c52fff3
 ID: AHB5:5WO6:SZUI:XY7Z:E35Y:TR4N:WCSU:O6HP:XZWA:FPOI:UTYZ:U5HO
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: ******
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: No swap limit support
+ /usr/local/bin/docker buildx create --use
tender_elgamal
+ /usr/local/bin/docker buildx ls
NAME/NODE         DRIVER/ENDPOINT             STATUS   PLATFORMS
tender_elgamal *  docker-container                     
  tender_elgamal0 unix:///var/run/docker.sock inactive 
default           docker                               
  default         default                     running  linux/amd64, linux/386
+ /usr/local/bin/docker buildx build --rm=true -f buildx/Dockerfile -t e0d58874f83305abd9f18e01445ad15dea56290e buildx --pull=true --build-arg DOCKER_IMAGE_CREATED=2021-07-01T08:25:54Z --push --platform linux/amd64,linux/arm64
#1 [internal] booting buildkit
#1 sha256:0a2ba0cd5ea8c52e79a7f93cbba408c05414cb8e17a43e9a13ce5940f8dd2fda
#1 pulling image moby/buildkit:buildx-stable-1
#1 pulling image moby/buildkit:buildx-stable-1 4.2s done
#1 creating container buildx_buildkit_tender_elgamal0
#1 creating container buildx_buildkit_tender_elgamal0 0.5s done
#1 DONE 4.7s

#2 [internal] load build definition from Dockerfile
#2 sha256:2d1b2c44f4abbc6fcad818c65f25288ef65b8364815b03fa5ce6c0eeecf2eb79
#2 transferring dockerfile: 51B done
#2 DONE 0.0s

#3 [internal] load .dockerignore
#3 sha256:3bb4aecf5946be306c314bb5f696e5fdf418405e11e4c17d4b06c43996e98830
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [linux/arm64 internal] load metadata for docker.io/library/alpine:3
#4 sha256:465f2ae407e66c1d886aa1b086067ab5048eaf45b9ab7cc4de8f65195ebcc132
#4 ...

#6 [auth] library/alpine:pull token for registry-1.docker.io
#6 sha256:d7f1e0da8ab5a59c023ba11dbf7f3693b7ff437619e975d0b93e9b22d1d6a1b8
#6 DONE 0.0s

#5 [linux/amd64 internal] load metadata for docker.io/library/alpine:3
#5 sha256:1b81b8e0cb240d69aea10317b964ca403e3026583df1ee104e71fb8b9192dfe5
#5 DONE 1.9s

#4 [linux/arm64 internal] load metadata for docker.io/library/alpine:3
#4 sha256:465f2ae407e66c1d886aa1b086067ab5048eaf45b9ab7cc4de8f65195ebcc132
#4 DONE 1.9s

#7 [linux/arm64 1/1] FROM docker.io/library/alpine:3@sha256:234cb88d3020898631af0ccbbcca9a66ae7306ecd30c9720690858c1b007d2a0
#7 sha256:ed2c270953b2750731b144e9c735f7fc32302891e45731e7c8e94a3afa2ffc8f
#7 resolve docker.io/library/alpine:3@sha256:234cb88d3020898631af0ccbbcca9a66ae7306ecd30c9720690858c1b007d2a0 done
#7 DONE 0.0s

#8 [linux/amd64 1/1] FROM docker.io/library/alpine:3@sha256:234cb88d3020898631af0ccbbcca9a66ae7306ecd30c9720690858c1b007d2a0
#8 sha256:5deda93350bce5d963e186041c03b9fc9f03d8e5168a66519c6b7fc41675107e
#8 resolve docker.io/library/alpine:3@sha256:234cb88d3020898631af0ccbbcca9a66ae7306ecd30c9720690858c1b007d2a0 done
#8 DONE 0.0s

#10 [auth] library/e0d58874f83305abd9f18e01445ad15dea56290e:pull,push token for registry-1.docker.io
#10 sha256:5aae3f914e2b312b0f24246d1a852c9a327bc12f0c53290767a9535fbb1a252c
#10 DONE 0.0s

#9 exporting to image
#9 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#9 exporting layers done
#9 exporting manifest sha256:c00627643b27aeec6fdcfce041f60a6cb36796250f966cff4575d32b4594639d done
#9 exporting config sha256:2b52538fc127808cb8cf80df47778b9cfc8bb367531c163a646d021cea92be35 done
#9 exporting manifest sha256:84f970a30e36f9b03f57e6510f25b9fa74229e2c377c8ee1a9e92c3aee63b69e done
#9 exporting config sha256:6729c91422712f0bc6801eabb83948c67126a7d5f19585a70586052216b17051 done
#9 exporting manifest list sha256:3367819ef60d6cac2734de3d7ac0fbbc22ab3c3cd0c0e9326f6a7665f25ff8e7 done
#9 pushing layers
#9 ...

#11 [auth] library/e0d58874f83305abd9f18e01445ad15dea56290e:pull,push token for registry-1.docker.io
#11 sha256:2f2d09e05cb3a6bf3d1d54826b2ff8050d9535a3bd2e6e000e2590b9e6543759
#11 DONE 0.0s

#12 [auth] library/e0d58874f83305abd9f18e01445ad15dea56290e:pull,push token for registry-1.docker.io
#12 sha256:8e7db6694b9c2233ad85b8caae0265d20a04d894e5a3962a98437276de4e5098
#12 DONE 0.0s

#13 [auth] library/alpine:pull library/e0d58874f83305abd9f18e01445ad15dea56290e:pull,push token for registry-1.docker.io
#13 sha256:1074b59be64ff22e12fbfae4d9b15af80244315fa4253145e6b2e1c903626a8f
#13 DONE 0.0s

#14 [auth] library/e0d58874f83305abd9f18e01445ad15dea56290e:pull,push token for registry-1.docker.io
#14 sha256:b2c6eea312aad072e67a30e0ce065490f0cb303fd436d86231222c1264a9d808
#14 DONE 0.0s

#9 exporting to image
#9 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#9 ...

#15 [auth] library/e0d58874f83305abd9f18e01445ad15dea56290e:pull,push token for registry-1.docker.io
#15 sha256:847cb71531d57d2571fc78c0e8498abe4df9c00b5272d00edd84bfdecaf3e175
#15 DONE 0.0s

#9 exporting to image
#9 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#9 pushing layers 1.2s done
#9 ERROR: server message: insufficient_scope: authorization failed
------
 > exporting to image:
------
error: failed to solve: rpc error: code = Unknown desc = server message: insufficient_scope: authorization failed
time="2021-07-01T08:26:02Z" level=error msg="execution failed: exit status 1"
```
