### ISSUE TITLE
Bad parsing secrets configuration

### ISSUE THREAD

**Issue by gregoire78** [thegeeklab/drone-docker-buildx#284]
Hello,

I have testing the secrets feature today and I have found a problem when I set secrets like this:

```yml
  settings:
    secrets: 
      - "id=secretid,src=mysrc"
      - "id=othersecertid"
```

The result of the command is like this : 

```sh
docker buildx build  [...] --secret id=secretid --secret src=mysrc --secret id=othersecertid
```

and should be like this :

```sh
docker buildx build  [...] --secret id=secretid,src=mysrc --secret id=othersecertid
```

`Secrets` is like `CacheFrom` for the format.

And then the settings become :

```yml
  settings:
    secrets: 
      - "id=secretid\\\\,src=mysrc"
      - 'id=secretida\\,src=mysrca'
      - "id=othersecertid"
```

Thanks for this feature :100:
