### ISSUE TITLE
Multi arch builds fail

### ISSUE THREAD

**Issue by modem7** [thegeeklab/drone-docker-buildx#41]
When trying multi-arch build, it's now failing, unsure on why?

Drone pipeline:
```
kind: pipeline
type: docker
name: deploy

platform:
  os: linux
  arch: amd64

steps:
- name: latest  
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    repo: modem7/dhcprelay
    purge: true
    compress: true
    cache_from: "modem7/dhcprelay:latest"
    platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: latest
```

Error:
https://drone.modem7.com/modem7/DHCP-Relay/19

The last time this worked was about 12 days ago (https://drone.modem7.com/modem7/DHCP-Relay/10/)

It could be an ID10T issue, so apologies if so, still quite new to drone. 

The build works with just linux/amd64 selected.
