### ISSUE TITLE
More beginner friendly doc

### ISSUE THREAD

**Issue by VeselaHouba** [thegeeklab/drone-docker-buildx#62]
Hi,
I've managed to get the plugin working, but it took me some time as I'm no expert in drone or docker buildx. Can you tell me if this pipeline is correctly defined? If so, can you include some basic "copy-paste" example in docu?

I don't want to install qemu support on OS level, so I install it during run. It's enough to install it once until next OS reboot, but running every time is more reliable.

```
---
kind: pipeline
name: default
steps:
  - name: dockerx prep
    image: thegeeklab/drone-docker-buildx
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - sleep 5
      - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

  - name: dockerx
    image: thegeeklab/drone-docker-buildx
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run
    settings:
      username: my-dh-user
      password:
        from_secret: MY_DH_SECRET
      repo: my-dh-repo/${DRONE_REPO_NAME/_/-}
      auto_tag: true
      platforms: linux/arm64/v8,linux/amd64

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

```

**Comment by VeselaHouba** [comment]
Found out most of the code is not needed, I was missing the `experimental`

This should do the trick, right?

```
kind: pipeline
name: default
steps:
  - name: dockerx
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      experimental: true
      username: my-dh-user
      password:
        from_secret: MY_DH_SECRET
      repo: my-dh-repo/${DRONE_REPO_NAME/_/-}
      auto_tag: true
      platforms: linux/arm64/v8,linux/amd64
```

**Comment by xoxys** [comment]
Hi,

I disagree a bit. This repo is a Drone CI Plugin. How Drone plugins work and how to define them in your pipeline is documented upstream already. There is absolutely nothing special to this plugin, the only thing that is a hard requirement is the `privileged` mode and that's already part of the plugin documentation as well as all available setting parameters.

The basic usage is:

```
 - name: Build
    pull: always
    image: thegeeklab/drone-docker-buildx:20
    settings:
      repo: thegeeklab/${DRONE_REPO_NAME}
      platforms:
        - linux/amd64
      username:
        from_secret: docker_username
      password:
       from_secret: docker_password
```

Everything else is optional and depends on your own environment. What exactly are you missing?
