### ISSUE TITLE
Buildx runners are not reused

### ISSUE THREAD

**Issue by Shanduur** [thegeeklab/drone-docker-buildx#77]
Buildx runners are hanging unused after execution finishes. There should be cleanup of them on the final part of the execution.

**Comment by xoxys** [comment]
Im not sure what do you mean by "hanging unused".  Can you explain it a bit more?

**Comment by Shanduur** [comment]
```
[opc@oracle ~]$ docker container ls
CONTAINER ID   IMAGE                           COMMAND                  CREATED              STATUS              PORTS                                                                                            NAMES
e043e467abdd   moby/buildkit:buildx-stable-1   "buildkitd"              About a minute ago   Up About a minute                                                                                                    buildx_buildkit_festive_sanderson0
0239fbce7b4e   moby/buildkit:buildx-stable-1   "buildkitd"              10 minutes ago       Up 10 minutes                                                                                                        buildx_buildkit_pensive_boyd0
2a975179381f   moby/buildkit:buildx-stable-1   "buildkitd"              14 minutes ago       Up 14 minutes                                                                                                        buildx_buildkit_ecstatic_edison0
812c03b6bf8f   moby/buildkit:buildx-stable-1   "buildkitd"              20 minutes ago       Up 20 minutes                                                                                                        buildx_buildkit_busy_volhard0
08f4f8d89b92   moby/buildkit:buildx-stable-1   "buildkitd"              24 minutes ago       Up 24 minutes                                                                                                        buildx_buildkit_great_swirles0
fc92a115007c   moby/buildkit:buildx-stable-1   "buildkitd"              29 minutes ago       Up 29 minutes                                                                                                        buildx_buildkit_unruffled_almeida0
df01615319d8   moby/buildkit:buildx-stable-1   "buildkitd"              2 hours ago          Up 2 hours                                                                                                           buildx_buildkit_cranky_mclaren0
9c7be84aa8fe   fb1d84dcf0bb                    "/bin/drone-server"      2 hours ago          Up 2 hours          0.0.0.0:8002->80/tcp, :::8002->80/tcp, 0.0.0.0:9002->443/tcp, :::9002->443/tcp                   drone_server_1
3b5509f217a0   c7496fe41b92                    "/bin/drone-runner-d…"   2 hours ago          Up 2 hours          0.0.0.0:3000->3000/tcp, :::3000->3000/tcp                                                        drone_runner_1
```

I have only single runner and single server. I enabled only one project, and it is running only one pipeline with `drone-docker-buildx`. Every new run creates new buildkit container that is neither removed nor used again.

**Comment by xoxys** [comment]
Im confused, it looks like you use `moby/buildkit:buildx-stable-1` which is a completely different image that is not related to this repo.

**Comment by Shanduur** [comment]
That's the repo: https://github.com/Shanduur/ddgo
Here is my Drone instance: http://130.61.100.100:8002/Shanduur/ddgo

As you can see in the `.dorne.yml`, I am using correct image:
```yml
kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: arm64

steps:
- name: publish
  image: thegeeklab/drone-docker-buildx
  privileged: true
  volumes:
  - name: docker
    path: /var/run/docker.sock
  settings:
    platforms:
      - linux/arm64
      - linux/amd64
    repo: shanduur/ddgo
    tags: [ "${DRONE_COMMIT_SHA:0:7}", "latest" ]
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
```
